service: import-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::shopproductscatalog"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::shopproductscatalog/*"
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
      Resource:
        - "arn:aws:sqs:${aws:region}:${aws:accountId}:product-service-dev-catalogItemsQueue"
  environment:
    catalogItemsQueueUrl: ${env:catalogItemsQueueUrl}

useDotenv: true

plugins:
  - serverless-webpack

functions:
  importProductsFile:
    handler: handlers/importProductsFile.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors:
            origins:
              - https://d1ty74fm6yb21c.cloudfront.net
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
              - pragma
              - cache-control
            allowCredentials: true
          request:
            parameters:
              querystrings:
                name: true
          authorizer: 
            arn: arn:aws:lambda:${aws:region}:${aws:accountId}:function:authorization-service-dev-basicAuthorizer
            type: token
            resultTtlInSeconds: 0
            identityValidationExpression: '^Basic .*'

  importFileParser:
    handler: handlers/importFileParser.importFileParser
    events:
      - s3:
          bucket: shopproductscatalog
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true

custom:
  webpack:
    webpackConfig: "webpack.config.js"
    includeModules: false
    packager: "npm"
